version: '3'

vars: 
  ROOMS:
    sh: echo $(ls data)
  TIME_WINDOWS: 30 45 60

tasks:
  format:
    desc: "format.py を実行する"
    cmds:
      - |
        for r in {{.ROOMS}}; do
          for tw in {{.TIME_WINDOWS}}; do
            python format.py -i data/$r -o formatted/${r%.*}_t=$tw -t $tw;
          done;
        done
  
  format_w:
    desc: "format.py を加重平均で実行する"
    cmds:
      - |
        for r in {{.ROOMS}}; do
          for tw in {{.TIME_WINDOWS}}; do
            python format.py -i data/$r -o formatted_w/${r%.*}_t=$tw -t $tw -w;
          done;
        done